# Generated by Django 5.1.1 on 2026-03-20 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО сотрудника')),
                ('token', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Ключ доступа')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Допущен')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.visitor')),
            ],
        ),
    ]
