# Generated by Django 5.1.1 on 2026-04-22 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО посетителя')),
                ('document_type', models.CharField(choices=[('passport_rf', 'Паспорт РФ'), ('car_plate', 'Автомобильный номер'), ('other', 'Другой документ')], max_length=50, verbose_name='Тип документа')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('escort_name', models.CharField(max_length=255, verbose_name='ФИО ответственного')),
                ('escort_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон ответственного')),
                ('valid_until', models.DateTimeField(verbose_name='Действует до')),
                ('kpp', models.CharField(choices=[('kpp1', 'КПП-1'), ('kpp2', 'КПП-2')], max_length=10, verbose_name='КПП')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Одобрено'), ('departed', 'Ушёл')], default='pending', max_length=20, verbose_name='Статус')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прихода')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Время ухода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpp', models.CharField(blank=True, choices=[('kpp1', 'КПП-1'), ('kpp2', 'КПП-2')], default='kpp1', max_length=10, null=True)),
                ('is_responsible', models.BooleanField(default=False, verbose_name='Ответственный')),
                ('responsible_full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО ответственного')),
                ('responsible_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон ответственного')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
