# Generated by Django 5.1.1 on 2026-03-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО полностью')),
                ('document_type', models.CharField(choices=[('passport_rf', 'Паспорт РФ'), ('international_passport', 'Загранпаспорт'), ('driver_license', 'Водительское удостоверение'), ('other', 'Другой документ')], default='passport_rf', max_length=30, verbose_name='Тип документа')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Допущен'), ('departed', 'Ушёл')], default='pending', max_length=10)),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прихода')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Время ухода')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accompanied_visitors', to='core.visitor')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
                'ordering': ['-created_at'],
            },
        ),
    ]
