# Generated by Django 5.1.1 on 2026-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='passport',
            field=models.CharField(max_length=50, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Одобрено'), ('rejected', 'Отказано')], default='pending', max_length=10),
        ),
    ]
